version: '3.8'

services:
  vineapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7901:8000"

# After starting, the service will be available at:
# - Web UI: http://localhost:7901
