services:
  vineapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7901:8000"
    networks:
      - serra-vine

networks:
  serra-vine:
    external: true

# After starting, the service will be available at:
# - Web UI: http://localhost:7901
