name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags
    
    - name: Set up Python {{cookiecutter.python_version}}
      uses: actions/setup-python@v3
      with:
        python-version: "{{cookiecutter.python_version}}"
    
    - name: Install dependencies
      run: |
        make update
    
    - name: Run quality checks and tests with coverage
      run: |
        make quality
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: {% raw %}${{ secrets.CODECOV_TOKEN }}{% endraw %}
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
