name: Package

on:
  push:
    tags: [ "v*" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for all branches and tags
    
    - name: Set image tags
      run: |
        echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
        echo "IMAGE_NAME={{cookiecutter.docker_registry}}/{{cookiecutter.docker_org}}/{{cookiecutter.project_slug}}" >> $GITHUB_ENV
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: {{cookiecutter.docker_registry}}
        username: {% raw %}${{ github.actor }}{% endraw %}
        password: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}
    
    - name: Build and tag Docker images
      run: |
        docker build -t {% raw %}${{ env.IMAGE_NAME }}{% endraw %}:{% raw %}${{ env.VERSION }}{% endraw %} -t {% raw %}${{ env.IMAGE_NAME }}{% endraw %}:latest .
    
    - name: Publish Docker images
      run: |
        docker push {% raw %}${{ env.IMAGE_NAME }}{% endraw %}:{% raw %}${{ env.VERSION }}{% endraw %}
        docker push {% raw %}${{ env.IMAGE_NAME }}{% endraw %}:latest
